#!/usr/bin/env python3
"""Generate font_chrono.h from 8x16 pixel art definitions.

Usage: python tools/gen_icons.py > src/font_chrono.h

Each glyph is an 8-wide x 16-tall grid. X = pixel on, . = pixel off.
SSD1306 column-major format: each byte is one column, bit0 = top pixel.
Upper page = rows 0-7, lower page = rows 8-15.
"""

import sys
from collections import OrderedDict

def pixels_to_bytes(art):
    rows = [line.strip() for line in art.strip().split('\n')]
    assert len(rows) == 16, f'Need 16 rows, got {len(rows)}'
    for i, r in enumerate(rows):
        assert len(r) == 8, f'Row {i} has {len(r)} cols: {repr(r)}'
    upper, lower = [], []
    for col in range(8):
        ubyte, lbyte = 0, 0
        for bit in range(8):
            if rows[bit][col] == 'X': ubyte |= (1 << bit)
            if rows[bit+8][col] == 'X': lbyte |= (1 << bit)
        upper.append(ubyte)
        lower.append(lbyte)
    return upper + lower

def fmt(data, comment):
    return '  ' + ','.join(f'0x{b:02X}' for b in data) + ', // ' + comment

# ============================================================
# GLYPH DEFINITIONS — edit pixel art here, then re-run script
# ============================================================
# Key format: (ascii_code, short_label)
# Art: 8 chars wide, 16 lines tall, X=on .=off

glyphs = OrderedDict()

# ---- SPACE ----
glyphs[(32, '  32 space')] = """
........
........
........
........
........
........
........
........
........
........
........
........
........
........
........
........
"""

# ---- ICON GLYPHS (placed in unused ASCII slots) ----

glyphs[(33, '! 33 hourglass (TIMER)')] = """
........
........
XXXXXXX.
.X...X..
..X.X...
...X....
...X....
..X.X...
.X...X..
XXXXXXX.
........
........
........
........
........
........
"""

glyphs[(34, '" 34 stopwatch (STOPWTCH)')] = """
........
...XX...
..XXXX..
..XXXX..
...XX...
..XX.X..
.X.X..X.
.X.X...X
...X....
..X.X...
..X..X..
.X...X..
.X...XXX
XXX.....
........
........
"""

glyphs[(35, '# 35 clock (CLOCK)')] = """
..XXXX..
.X....X.
X...x.X.
X...X..X
X...X..X
X...x..X
X.XXx..X
X......X
X......X
X......X
.X....X.
..XXXX..
........
........
........
........
"""

glyphs[(36, '$ 36 bell (ALARM)')] = """
........
....XX..
....XXx.
....XX.x
....XX.x
....XX.x
....XX..
..XXXX..
.X..XX..
.X..XX..
..XXX...
........
........
........
........
........
"""

glyphs[(37, '% 37 checkmark (OK)')] = """
........
........
........
.......X
......X.
......X.
.....X..
.....X..
X...X...
XX..X...
.X.X....
.XXX....
..XX....
..X.....
........
........
"""

glyphs[(38, '& 38 plus (+1)')] = """
........
........
........
...XX...
...XX...
.XXXXXX.
.XXXXXX.
...XX...
...XX...
........
........
........
........
........
........
........
"""

glyphs[(39, "' 39 minus (-1)")] = """
........
........
........
........
........
.XXXXXX.
.XXXXXX.
........
........
........
........
........
........
........
........
........
"""

glyphs[(40, '( 40 play (START/GO)')] = """
........
.X......
.XX.....
.XXX....
.XXXX...
.XXXXX..
.XXXXXX.
.XXXXXXX
.XXXXXXX
.XXXXXX.
.XXXXX..
.XXXX...
.XXX....
.XX.....
.X......
........
"""

glyphs[(41, ') 41 stop (STOP)')] = """
........
........
.XXXXXX.
.XXXXXX.
.XXXXXX.
.XXXXXX.
.XXXXXX.
.XXXXXX.
.XXXXXX.
.XXXXXX.
.XXXXXX.
.XXXXXX.
.XXXXXX.
.XXXXXX.
........
........
"""

# * and + are unused but must exist in the contiguous range 32-58.
# Keeping original font data for these slots.

glyphs[(42, '* 42 (unused)')] = """
........
.X.X.X..
..XXX...
.XXXXX..
..XXX...
.X.X.X..
........
........
........
........
........
........
........
........
........
........
"""

glyphs[(43, '+ 43 (unused)')] = """
........
........
...X....
...X....
...X....
.XXXXX..
...X....
...X....
...X....
........
........
........
........
........
........
........
"""

glyphs[(44, ', 44 flag (LAP)')] = """
..X.....
..XXXXXX
..XXXXXX
..XXXXXX
..XXXXXX
..X.....
..X.....
..X.....
..X.....
..X.....
..X.....
..X.....
..X.....
..X.....
.XXX....
........
"""

glyphs[(45, '- 45 caret (setting indicator)')] = """
........
........
...XX...
..XXXX..
.XXXXXX.
........
........
........
........
........
........
........
........
........
........
........
"""

glyphs[(46, '. 46 reset (RESET)')] = """
........
..XXXX..
.X....X.
X.....XX
X....XXX
X......X
X......X
.X....X.
..XXXX..
........
........
X.......
XX......
XXX.....
........
........
"""

glyphs[(47, '/ 47 xmark (OFF)')] = """
........
X.....X.
XX...XX.
.XX.XX..
..XXX...
...X....
..XXX...
.XX.XX..
XX...XX.
X.....X.
........
........
........
........
........
........
"""

# ---- DIGITS 0-9 and COLON (kept from original FONT8X16) ----

glyphs[(48, '0 48')] = """
..XXX...
.X...X..
X.....X.
X.....X.
X.....X.
X.....X.
X.....X.
X.....X.
X.....X.
X.....X.
X.....X.
X.....X.
.X...X..
..XXX...
........
........
"""

glyphs[(49, '1 49')] = """
...X....
..XX....
.X.X....
...X....
...X....
...X....
...X....
...X....
...X....
...X....
...X....
...X....
...X....
.XXXXX..
........
........
"""

glyphs[(50, '2 50')] = """
..XXX...
.X...X..
X.....X.
......X.
.....X..
....X...
...X....
..X.....
.X......
X.......
X.......
X.....X.
XXXXXXX.
........
........
........
"""

glyphs[(51, '3 51')] = """
..XXX...
.X...X..
X.....X.
......X.
......X.
...XXX..
......X.
......X.
......X.
......X.
X.....X.
.X...X..
..XXX...
........
........
........
"""

glyphs[(52, '4 52')] = """
.....X..
....XX..
...X.X..
..X..X..
.X...X..
X....X..
X....X..
XXXXXXX.
.....X..
.....X..
.....X..
.....X..
.....X..
........
........
........
"""

glyphs[(53, '5 53')] = """
XXXXXXX.
X.......
X.......
X.......
XXXXXX..
......X.
......X.
......X.
......X.
......X.
......X.
X....X..
.XXXX...
........
........
........
"""

glyphs[(54, '6 54')] = """
..XXX...
.X...X..
X.......
X.......
X.XXX...
XX...X..
X.....X.
X.....X.
X.....X.
X.....X.
.X...X..
..XXX...
........
........
........
........
"""

glyphs[(55, '7 55')] = """
XXXXXXX.
X.....X.
......X.
.....X..
.....X..
....X...
....X...
...X....
...X....
..X.....
..X.....
..X.....
........
........
........
........
"""

glyphs[(56, '8 56')] = """
..XXX...
.X...X..
X.....X.
X.....X.
.X...X..
..XXX...
.X...X..
X.....X.
X.....X.
X.....X.
X.....X.
.X...X..
..XXX...
........
........
........
"""

glyphs[(57, '9 57')] = """
..XXX...
.X...X..
X.....X.
X.....X.
X.....X.
.X...X..
..XXX.X.
......X.
......X.
......X.
.....X..
....X...
..XX....
........
........
........
"""

glyphs[(58, ': 58')] = """
........
........
........
...XX...
...XX...
........
........
........
........
........
...XX...
...XX...
........
........
........
........
"""

# ============================================================
# GENERATE font_chrono.h
# ============================================================

HEADER = """#pragma once
#include <avr/pgmspace.h>
#include <Tiny4kOLED_common.h>

// Custom 8x16 font: ASCII 32-58 (space through colon)
// 27 glyphs x 16 bytes = 432 bytes
//
// Symbol icons in unused ASCII slots:
//   ! hourglass (TIMER)    " stopwatch (STOPWTCH)  # clock (CLOCK)
//   $ bell (ALARM)         % checkmark (OK)        & plus (+1)
//   ' minus (-1)           ( play (START/GO)       ) stop (STOP)
//   , flag (LAP)           - caret (setting indicator)
//   . reset (RESET)        / X-mark (OFF)
//
// Generated by tools/gen_icons.py — edit pixel art there, not here.
const uint8_t chrono_font_data[] PROGMEM = {
"""

FOOTER = """};

const DCfont chronoFont = {
  (uint8_t *)chrono_font_data,
  8,  // width in pixels
  2,  // height in pages (8 pixels each)
  32, // first ASCII
  58, // last ASCII
  0, 0, 0
};

#define FONT_CHRONO (&chronoFont)
"""

def main():
    # Use existing compiled data for digits (from original FONT8X16).
    # These are the canonical bitmaps — pixel art above is approximate.
    digit_overrides = {
        48: [0x00,0xE0,0x10,0x08,0x08,0x10,0xE0,0x00,0x00,0x0F,0x10,0x20,0x20,0x10,0x0F,0x00],
        49: [0x00,0x10,0x10,0xF8,0x00,0x00,0x00,0x00,0x00,0x20,0x20,0x3F,0x20,0x20,0x00,0x00],
        50: [0x00,0x70,0x08,0x08,0x08,0x88,0x70,0x00,0x00,0x30,0x28,0x24,0x22,0x21,0x30,0x00],
        51: [0x00,0x30,0x08,0x88,0x88,0x48,0x30,0x00,0x00,0x18,0x20,0x20,0x20,0x11,0x0E,0x00],
        52: [0x00,0x00,0xC0,0x20,0x10,0xF8,0x00,0x00,0x00,0x07,0x04,0x24,0x24,0x3F,0x24,0x00],
        53: [0x00,0xF8,0x08,0x88,0x88,0x08,0x08,0x00,0x00,0x19,0x21,0x20,0x20,0x11,0x0E,0x00],
        54: [0x00,0xE0,0x10,0x88,0x88,0x18,0x00,0x00,0x00,0x0F,0x11,0x20,0x20,0x11,0x0E,0x00],
        55: [0x00,0x38,0x08,0x08,0xC8,0x38,0x08,0x00,0x00,0x00,0x00,0x3F,0x00,0x00,0x00,0x00],
        56: [0x00,0x70,0x88,0x08,0x08,0x88,0x70,0x00,0x00,0x1C,0x22,0x21,0x21,0x22,0x1C,0x00],
        57: [0x00,0xE0,0x10,0x08,0x08,0x10,0xE0,0x00,0x00,0x00,0x31,0x22,0x22,0x11,0x0F,0x00],
        58: [0x00,0x00,0x00,0xC0,0xC0,0x00,0x00,0x00,0x00,0x00,0x00,0x30,0x30,0x00,0x00,0x00],
    }

    lines = []
    for (code, label), art in glyphs.items():
        if code in digit_overrides:
            data = digit_overrides[code]
        else:
            data = pixels_to_bytes(art)
        lines.append(fmt(data, label))

    output = HEADER + '\n'.join(lines) + '\n' + FOOTER

    # Write to src/font_chrono.h (run from project root)
    import os
    out_path = os.path.join(os.path.dirname(__file__), '..', 'src', 'font_chrono.h')
    out_path = os.path.normpath(out_path)
    with open(out_path, 'w', newline='\n') as f:
        f.write(output)
    print(f'Wrote {out_path}')
    print(f'  {len(glyphs)} glyphs, {len(glyphs) * 16} bytes PROGMEM')

if __name__ == '__main__':
    main()
